name: conekta_component
description: A Flutter library for securely collecting and validating card payment information using Conekta.
version: 1.0.1
homepage: https://www.github.com/conekta/component-flutter
repository: https://www.github.com/conekta/component-flutter
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^0.13.6
  flutter_svg: ^2.0.0
  google_fonts: ^4.0.0
  encrypt: ^5.0.0
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_test:
      sdk: flutter
  test: ^1.16.0
flutter:
  generate: true
  assets:
    - test/assets/conekta-logo-blue-full.svg
platforms:
  android:
  ios:
  web:
