name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Run Flutter unit and widget tests
        run: flutter test
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          heap-size: 1024M
          disable-animations: false
          cores: 8
          ram-size: 12288M
          target: google_apis
          arch: x86_64
          profile: pixel
          script: flutter test integration_test/
